### PR TITLE
Fix Ctrl+C exit delay and improve display update behaviour

### LINKED ISSUE #34: Fix Control C event handler
Event C handler currently not working properly, works with delay/lag

Responsiveness tested in:
- _Sending Normally_ (requires more testing)
- Graph
- _Flood_  (requires more testing)
- Scan

### PR DESCRIPTION
**Pull request by jdpurcell**
Fix #34 and some other fixes/improvements.

### CODE REVIEW

File: .editorconfig [hunk 1]
```diff
@@ -1,6 +1,6 @@
...
-
-[*]
-indent_style = space
-indent_size = 4
+# top-most EditorConfig file
+root = true
+
+[*]
+indent_style = space
+indent_size = 4
```
Comment (jdpurcell) [inline .editorconfig]: This whole file shows as changed because I changed the newlines from CR/LF to LF to match all the other files in your repo.

File: .gitattributes [hunk 2]
```diff
@@ -0,0 +1,2 @@
+# Enable automatic end-of-line normalization
+* text=auto
```
Comment (jdpurcell) [inline .gitattributes]: You apparently have Git's autocrlf setting enabled on your local install. I always disable the setting on mine. This .gitattributes file is a way to specify the setting on a per-repo level so everyone has the same settings regardless of their system default.

Without this, Git checks out all files with LF line ending on my machine, which causes some annoyances like Visual Studio changing the whole .csproj every time I add a new file to convert all the line endings to CR/LF.

File: src/PowerPing/Graph.cs [hunk 3]
```diff
@@ -63,16 +61,21 @@ class Graph : IDisposable
...
             // Setup ping attributes
             graphPingAttrs.Host = PowerPing.Lookup.QueryDNS(address, System.Net.Sockets.AddressFamily.InterNetwork);
             graphPingAttrs.Continous = true;
-            Display.ShowOutput = false;
         }
 
         public void Start()
         {
+            // Disable output
+            Display.ShowOutput = false;
```
Comment (jdpurcell) [inline src/PowerPing/Graph.cs]: Used to be in the constructor but this seemed like a better place.

File: src/PowerPing/Graph.cs [hunk 4]
```diff
@@ -83,27 +86,24 @@ public void Start()
 
             // Start drawing graph
             Draw();
+
+            // Show cursor
+            Console.CursorVisible = true;
```
Comment (jdpurcell) [inline src/PowerPing/Graph.cs]: Used to be in Dispose.

File: src/PowerPing/Ping.cs [hunk 5]
```diff
@@ -365,13 +345,18 @@ private PingResults SendICMP(PingAttributes attrs)
...
             // Sending loop
-            while (attrs.Continous ? true : index <= attrs.Count) {
+            for (int index = 1; attrs.Continous || index <= attrs.Count; index++) {
 
-                // Exit loop if cancel event is set
-                if (cancelEvent.WaitOne(0)) {
-                    break;
-                } else {
-                    IsRunning = true;
+                if (index != 1) {
```
Comment (jdpurcell) [inline src/PowerPing/Ping.cs]: The wait used to happen unconditionally at the end of the loop. I wanted to eliminate the pause after the final ping and this is the most elegant way to do it in my opinion.

File: src/PowerPing/Ping.cs [hunk 6]
```diff
@@ -398,14 +383,14 @@ private PingResults SendICMP(PingAttributes attrs)
 
                     // If there were extra responses from a prior request, ignore them
                     while (sock.Available != 0) {
-                        bytesRead = sock.ReceiveFrom(receiveBuffer, ref ep);
+                        bytesRead = sock.Receive(receiveBuffer);
```
Comment (jdpurcell) [inline src/PowerPing/Ping.cs]: We don't care about the from address in this case.

File: src/PowerPing/PingResults.cs [hunk 7]
```diff
@@ -50,7 +50,7 @@ public class PingResults
 
         // Local variables
         private readonly Stopwatch operationTimer = new Stopwatch();
-        private ulong sum  = 0; // Sum off all reply times
+        private double sum = 0; // Sum of all reply times
```
Comment (jdpurcell) [inline src/PowerPing/PingResults.cs]: Increase accuracy of averages - don't round each ping to a whole millisecond first. I noticed this inaccuracy when I was pinging my router (sub-millisecond responses).

File: src/PowerPing/Program.cs [hunk 8]
```diff
@@ -555,34 +555,29 @@ static void Main(string[] args)
...
-                    });
-                    thread.Start();
+                    p.Send(attributes);
                     break;
             }
-           
+
+            // Reset console colour
+            Display.ResetColor();
+            Console.CursorVisible = true;
```
Comment (jdpurcell) [inline src/PowerPing/Program.cs]: Used to be in the exit handler. Now the calls inside the case statement are blocking, and once the cancellation token is set those calls will finish gracefully and proceed to run this bit.

**Comment by jdpurcell** [comment]
@Killeroo Regarding the AppVeyor build failing, can you update it to use a newer MSBuild version? I used a newer language feature (local functions) that's causing it to fail. I can switch them to use lambdas instead if necessary, but local functions have more elegant syntax and are better performing.

File: src/PowerPing/Ping.cs [hunk 9]
```diff
@@ -253,33 +248,27 @@ public void Flood(string address)
...
             Display.ShowOutput = false;
 
-            // Start flood thread
-            var thread = new Thread(() => {
-                p.Send(attrs);
-            });
-            thread.IsBackground = true;
-            thread.Start();
-            IsRunning = true;
+            var limiter = new DisplayUpdateLimiter(TimeSpan.FromMilliseconds(500));
```
[the remark this answers is not in the document]
Comment (Killeroo) [reply src/PowerPing/Ping.cs]: I'm generally against using 'var' unless the variable type is quite clearly known (like it is here), just a minor point.

File: src/PowerPing/Ping.cs [hunk 10]
```diff
@@ -365,13 +344,18 @@ private PingResults SendICMP(PingAttributes attrs)
             packetSize = packet.messageSize + 4;
 
             // Sending loop
-            while (attrs.Continous ? true : index <= attrs.Count) {
+            for (int index = 1; attrs.Continous || index <= attrs.Count; index++) {
```
Comment (Killeroo) [inline src/PowerPing/Ping.cs]: Yeah for loop with this logic makes more sense than a while loop here.

File: src/PowerPing/Ping.cs (hunk 5 above)
Comment (Killeroo) [reply src/PowerPing/Ping.cs]: Ah ok I understand what you mean, it does make more sense to do it at the start of the loop. 

So why don't we want to run it on 1st run of the loop exactly? Is it because you don't want a delay when sending the first ping?

File: src/PowerPing/Ping.cs [hunk 11]
```diff
@@ -415,38 +399,54 @@ private PingResults SendICMP(PingAttributes attrs)
...
                     ICMP response;
-                    TimeSpan replyTime;
+                    EndPoint responseEP = iep;
+                    TimeSpan replyTime = TimeSpan.Zero;
                     do {
+                        // Cancel if requested
+                        cancellationToken.ThrowIfCancellationRequested();
+
+                        // Set receive timeout
+                        int remainingTimeout = (int)Math.Ceiling(attrs.Timeout - replyTime.TotalMilliseconds);
```
Comment (Killeroo) [inline src/PowerPing/Ping.cs]: I'm not sure if I like this, calling a math function like this I'm worried about the performance implications (maybe I'm overestimating .NETs overhead) and generally I'm not sure what the benefit of chopping up the timeout like this, is it so we can get quicker control-c? Just seems to be quite a bit of added math logic in general in this loop.

File: src/PowerPing/Ping.cs [hunk 12]
```diff
@@ -415,38 +399,54 @@ private PingResults SendICMP(PingAttributes attrs)
...
+                        if (remainingTimeout <= 0) {
+                            throw new SocketException();
+                        }
+                        sock.SetSocketOption(SocketOptionLevel.Socket, SocketOptionName.ReceiveTimeout, Math.Min(remainingTimeout, 250));
```
Comment (Killeroo) [inline src/PowerPing/Ping.cs]: So each iteration of this do..while we are decrementing the overall timeout by 250ms, yet we are setting the socket timeout each time. Doesn't seem right, because most iterations we are going to be unnecessarily calling setSocketOption to set the same value (250). Even if we have to use conditional logic to work around that I think its better and faster than using method or object calls too much.

Also like I mentioned, maybe I'm alergic to System.Net.Math but couldn't we just inline it here to use remainingTime if its less than 250?

` sock.SetSocketOption(SocketOptionLevel.Socket, SocketOptionName.ReceiveTimeout, remainingTimeout > 250 ? 250 : remainingTimeout);`

Like I bet the Math library is pretty fast but in general I really want to avoid unnecessary overhead if at all possible in this part of the code and keep this core sending/recieving loop as object light as it can be.

File: src/PowerPing/Ping.cs [hunk 13]
```diff
@@ -415,38 +399,54 @@ private PingResults SendICMP(PingAttributes attrs)
...
-                            if (responseSessionId != sessionId || responseSequenceNum != sequenceNum) {
-                                if (replyTime.TotalMilliseconds >= attrs.Timeout) {
-                                    throw new SocketException();
+                        if (bytesRead == 0) {
+                            response = null;
+                        } else {
+                            // Store reply packet
+                            response = new ICMP(receiveBuffer, bytesRead);
+
+                            // Ignore unexpected echo responses
```
Comment (Killeroo) [inline src/PowerPing/Ping.cs]: If feel like we should clarify that we are ignoring unexpected echo responses under normal sending conditions.

File: src/PowerPing/Ping.cs [hunk 14]
```diff
@@ -415,38 +399,54 @@ private PingResults SendICMP(PingAttributes attrs)
...
-                    try { Results.Received++; }
-                    catch (OverflowException) { Results.HasOverflowed = true; }
-                    Results.CountPacketType(response.type);
-                    Results.SaveResponseTime(replyTime.TotalMilliseconds);
+                    try { results.Received++; }
+                    catch (OverflowException) { results.HasOverflowed = true; }
+                    results.CountPacketType(response.type);
+                    results.SaveResponseTime(replyTime.TotalMilliseconds);
                     
 		            if (attrs.BeepLevel == 2) {
```
Comment (Killeroo) [inline src/PowerPing/Ping.cs]: Indentations a bit weird here. Don't know how long thats been that way for 😛

File: src/PowerPing/Ping.cs [hunk 15]
```diff
@@ -457,85 +457,50 @@ private PingResults SendICMP(PingAttributes attrs)
...
-                    Results.SaveResponseTime(-1);
-                    try { Results.Lost++; }
-                    catch (OverflowException) { Results.HasOverflowed = true; }
+                    results.SaveResponseTime(-1);
+                    try { results.Lost++; }
+                    catch (OverflowException) { results.HasOverflowed = true; }
+
+                } catch (OperationCanceledException) {
+
+                    break;
```
Comment (Killeroo) [inline src/PowerPing/Ping.cs]: Feel like we could specify that this break is for when user cancels the operation but I suppose the variables around tell that story so it's kind of a moot point.

File: src/PowerPing/Ping.cs [hunk 16]
```diff
@@ -457,85 +457,50 @@ private PingResults SendICMP(PingAttributes attrs)
...
-                    if (attrs.RandomTiming) {
-                        attrs.Interval = Helper.RandomInt(5000, 100000);
-                    }
                 }
 
-                // Stop sending if flag is set
-                if (!IsRunning) {
-                    break;
-                }
+                onResultsUpdate?.Invoke(results);
```
Comment (Killeroo) [inline src/PowerPing/Ping.cs]: Now that I understand how these events/callbacks are being used for I really like them here. Maybe just add a comment to say we are firing an callback?

File: src/PowerPing/PingResults.cs (hunk 7 above)
Comment (Killeroo) [reply src/PowerPing/PingResults.cs]: Yeah makes sense, especially as we are handling doubles in SaveResponsetime good idea to cut out the unneeded casting and loss of accuracy.

File: src/PowerPing/Program.cs [hunk 17]
```diff
@@ -555,34 +555,29 @@ static void Main(string[] args)
...
-                    });
-                    thread.Start();
+                    p.Flood(attributes.Host);
                     break;
                 case "scanning":
                     p.Scan(args.Last());
                     break;
                 default:
                     // Send ping normally
-                    thread = new Thread(() =>
```
Comment (Killeroo) [inline src/PowerPing/Program.cs]: Yeah thank god we aren't doing this anymore. Doesn't look good.

File: src/PowerPing/Program.cs (hunk 8 above)
Comment (Killeroo) [reply src/PowerPing/Program.cs]: Excellent 👍

File: src/PowerPing/Ping.cs [hunk 18]
```diff
@@ -110,12 +111,12 @@ public void Listen()
...
 
                 // Listening loop
-                while (true) {
+                while (!cancellationToken.IsCancellationRequested) {
                     byte[] buffer = new byte[4096]; // TODO: could cause overflow?
                     
                     // Recieve any incoming ICMPv4 packets
                     EndPoint remoteEndPoint = new IPEndPoint(IPAddress.Any, 0);
-                    int bytesRead = listeningSocket.ReceiveFrom(buffer, ref remoteEndPoint);
+                    int bytesRead = Task.Run(() => listeningSocket.ReceiveFrom(buffer, ref remoteEndPoint)).WaitForResult(cancellationToken);
```
Comment (Killeroo) [inline src/PowerPing/Ping.cs]: Sorry forgot to go back to this function in the review, again might be nice to have a comment explaining whats going on on here.

File: src/PowerPing/Ping.cs [hunk 19]
```diff
@@ -137,10 +135,10 @@ public void Listen()
             }
 
             // Clean up
-            IsRunning = false;
             listeningSocket.Close();
 
-            Display.ListenResults(results);
+            // TODO: Implement ListenResults method
+            //Display.ListenResults(results);
```
[the remark this answers is not in the document]
Comment (Killeroo) [reply src/PowerPing/Ping.cs]: Yeah that silly I left that call in, I had originally wanted to implement some sort of results display for the listening function. But I realised that its not really required as much, the listening function is more of a realtime thing, but might looking into adding some sort of custom results thing at some point.

File: src/PowerPing/Ping.cs (hunk 5 above)
Comment (jdpurcell) [reply src/PowerPing/Ping.cs]: Exactly, we only want to pause in between pings:
Ping 1 -- (Pause) -- Ping 2 -- (Pause) -- Ping 3
So depending where the pause is in the loop, we need to skip it on either the first or last iteration. If I kept the pause at the bottom of the loop, the 'if' logic would have been more complicated:
if (attrs.Continuous || index != attrs.Count) // Pause

File: src/PowerPing/DisplayUpdateLimiter.cs [hunk 20]
```diff
@@ -0,0 +1,55 @@
...
+        {
+            minimumUpdateIntervalTicks = Helper.TimeSpanToStopwatchTicks(minimumUpdateInterval.Ticks);
+        }
+
+        public TimeSpan? ElapsedSinceLastUpdate { get; private set; }
+
+        public bool RequestUpdate()
+        {
+            long currentTimestamp = Stopwatch.GetTimestamp();
+            long? elapsed = currentTimestamp - lastUpdateTimestamp;
```
[the remark this answers is not in the document]
Comment (jdpurcell) [reply src/PowerPing/DisplayUpdateLimiter.cs]: Question mark after the type indicates that it's a nullable type. Of course classes (e.g. strings) are inherently nullable, but anything that's a value type (struct) needs the question mark if you want to assign it null.

Maybe this code is being too 'clever' though. I am relying on the fact that math like "a - b" may result in null if either 'a' or 'b' is null. Because lastUpdateTimestamp may be null if this is the first update.

File: src/PowerPing/ExtensionMethods.cs [hunk 21]
```diff
@@ -0,0 +1,43 @@
...
+
+namespace PowerPing
+{
+    static class ExtensionMethods
+    {
+        public static T WaitForResult<T>(this Task<T> task, CancellationToken cancellationToken)
+        {
+            try {
+                task.Wait(cancellationToken);
+            } catch (AggregateException ex) when (ex.InnerExceptions.Count == 1) {
```
[the remark this answers is not in the document]
Comment (jdpurcell) [reply src/PowerPing/ExtensionMethods.cs]: Task.Wait wraps everything in an AggregateException. I am 'unwrapping' it here so we get the original exception type back. Before my last commit, this was important because the BeginReceive task could throw a SocketException, and there was code at the bottom of SendICMP to catch that SocketException, which wouldn't have worked if it was still wrapped in an AggregateException.

File: src/PowerPing/Ping.cs [hunk 22]
```diff
@@ -457,85 +457,50 @@ private PingResults SendICMP(PingAttributes attrs)
...
-                System.GC.Collect();
-
-                disposedValue = true;
-            }
+            return results;
         }
 
-        // This code added to correctly implement the disposable pattern.
-        public void Dispose()
+        public class ActiveHost
```
[the remark this answers is not in the document]
Comment (jdpurcell) [reply src/PowerPing/Ping.cs]: I would have put it in its own file like PingAttributes or PingResults or whatever, but I was just avoiding making a new file with a 24 line copyright header to hold such a small class 😂.

File: src/PowerPing/Ping.cs [hunk 23]
```diff
@@ -207,39 +203,38 @@ public void Scan(string range, bool recursing = false)
...
-                    activeHostTimes.Add(results.CurTime);
+            try {
+                // Scan loop
+                foreach (string host in scanList) {
+                    // Update host
+                    attrs.Address = host;
+
+                    // Send ping
+                    PingResults results = SendICMP(attrs);
+                    cancellationToken.ThrowIfCancellationRequested();
```
[the remark this answers is not in the document]
Comment (jdpurcell) [reply src/PowerPing/Ping.cs]: Exactly, it's just to break out of the loop in case SendICMP also stopped early before collecting all the results.

File: src/PowerPing/Ping.cs [hunk 24]
```diff
@@ -253,33 +248,27 @@ public void Flood(string address)
...
+                if (!limiter.RequestUpdate()) {
+                    return;
+                }
 
-            // Results loop 
-            while (IsRunning) {
-                // Update results text
-                Display.FloodProgress(p.Results, address);
+                // Calculate pings per second
+                double? pingsPerSecond = (r.Sent - previousPingsSent) / limiter.ElapsedSinceLastUpdate?.TotalSeconds;
```
[the remark this answers is not in the document]
Comment (jdpurcell) [reply src/PowerPing/Ping.cs]: In this context the question mark is called the null-propagation operator, which makes TotalSeconds return a nullable double instead of throwing a NullReferenceException if ElapsedSinceLastUpdate is null. In turn, it also makes the division calculation result in null.

If I weren't using nullable types here, there would need to be logic to avoid divide by zero since ElapsedSinceLastUpdate would be presumably zero on the very first update.

File: src/PowerPing/Ping.cs (hunk 12 above)
Comment (jdpurcell) [reply src/PowerPing/Ping.cs]: Yeah I should probably add logic to set the timeout only if it's changing. I did it that was just for simplicity as I didn't think it would affect performance too much.

As for inlining Math.Min, it's definitely not necessary. If you look at the code on Reference Source, it's just "return (val1<=val2)?val1:val2;", and I verified on SharpLab.io by checking the JIT Asm output that the JIT automatically inlines it.

File: src/PowerPing/Ping.cs (hunk 14 above)
Comment (jdpurcell) [reply src/PowerPing/Ping.cs]: Yeah it was already like that, you have some tabs mixed in with your spaces.

File: src/PowerPing/Ping.cs (hunk 11 above)
Comment (jdpurcell) [reply src/PowerPing/Ping.cs]: If the socket timeout is long, let's say 5 seconds, there is no way to check the cancel signal if the receive operation is happening synchronously in the same thread.

My first workaround was to wrap Task.Run around it, which basically runs it in a separate thread and allows you to check the cancel signal in the first thread while waiting for the second thread to finish. But this adds a small latency to coordinate the threads. For example when I did some benchmarks pinging localhost, the response time went from 0.02ms to 0.07ms.

Chopping up the timeout allows us to check the cancel signal every 250ms without having to run the receive in a separate thread.

File: src/PowerPing/Helper.cs [hunk 25]
```diff
@@ -36,6 +36,7 @@ namespace PowerPing
     public static class Helper
     {
         private static readonly double stopwatchToTimeSpanTicksScale = (double)TimeSpan.TicksPerSecond / Stopwatch.Frequency;
+        private static readonly double timeSpanToStopwatchTicksScale = (double)Stopwatch.Frequency / TimeSpan.TicksPerSecond;
```
[the remark this answers is not in the document]
Comment (jdpurcell) [reply src/PowerPing/Helper.cs]: Just to clarify: the existing method (Helper.StopwatchToTimeSpanTicks) actually is called inside RequestUpdate, but only inside the 'if' which happens once every display update (500ms or whatever), so I avoided having to call it every time.

**Comment by jdpurcell** [comment]
@Killeroo I think my latest push takes care of everything. Let me know if there's anything else if or you have any questions.

**Comment by Killeroo** [comment]
@jdpurcell Yeah perfect, that commits solves everything for me. I'm more than happy to merge this.

Now with this fix I think we are basically all set to release 1.3.0. I'd like to deal with https://github.com/Killeroo/PowerPing/issues/101 and then after that I think we are good to go. So yeah if you notice anything up with the current version of the code then feel free to add an issue.

Anyway good work the PR, I think its a really solid addition.
